# Generated by Django 5.0.4 on 2024-05-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="volunteer_ids",
        ),
    ]
