# Generated by Django 5.0.4 on 2024-05-13 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_remove_post_volunteer_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="volunteer_ids",
            field=models.ManyToManyField(
                blank=True,
                related_name="volunteered_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
